name: Build and Push image

on:
  workflow_call:
    inputs:
      service:
        required: false
        type: string
        description: 'Service name'
      GAR:
       required: true
       type: string
       description: 'Artifact Registry Path'
      env-vars:
        required: false
        type: string
        description: 'extra environment varaiables'
      region:
        required: false
        type: string
        description: 'repository region'
      project_id:
        required: false
        type: string
        description: 'GKE Cluster project id'
      service-name:
        required: true
        type: string
        description: 'Cloud Run service name'
      docker_img_name:
        required: true
        type: string
        description: 'Docker image name which you using for deployment'
      cpu:
        required: false
        default: 1
        type: string
        description: 'CPU size to allocate to instances'
      memory:
        required: false
        default: 1Gi
        type: string
        description: 'CPU size to allocate to instances'
      minimum_instances:
        required: false
        type: string
        description: 'Minimum instances limit add here'
      network_name:
        required: false
        type: string
        description: 'Provide VPC Name'
      subnet_name:
        required: false
        type: string
        description: 'Provide subnet name'
      cr-vars:
        required: false
        type: string
        description: 'extra environment varaiables'
      env-secrets:
        required: false
        type: string
        description: 'extra environment varaiables secrets which fetching from Secret Manager'
  
    secrets:
      GCP_CREDENTIALS:
        required: false
        description: 'GCP credentials'

jobs:
  build_test_push_cloudrun:
    runs-on: ubuntu-latest
    outputs:
      image_id: ${{ steps.push.outputs.image_id }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: "GCP Configuration"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          project_id: "${{ inputs.project_id }}"

      - name: "Docker auth"
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
          
      - name: Build image
        run: |
          docker build -t grafana ./src/services/backend
        working-directory: ${{ github.workspace }}

      - name: Tag Docker image with GitHub Actions run number
        id: tag_image
        run: |
          RUN_NUMBER=$(echo ${{ github.run_number }} | cut -c 1-7)
          IMAGE_TAG=${{ inputs.GAR }}/${{ inputs.docker_img_name }}:${RUN_NUMBER}
          echo "Tagging Docker image with tag: ${IMAGE_TAG}"
          docker tag ${{ inputs.docker_img_name }} ${IMAGE_TAG}

      - name: Push Docker image to GAR
        run: |
          RUN_NUMBER=$(echo ${{ github.run_number }} | cut -c 1-7)
          docker push ${{ inputs.GAR }}/${{ inputs.docker_img_name }}:${RUN_NUMBER}
 
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2.4.1'
        with:
          service: ${{ inputs.service-name }}
          project_id: ${{ inputs.project_id }}
          image: ${{ inputs.GAR }}/${{ inputs.docker_img_name }}:${{ github.run_number }}
          region: "${{ inputs.region }}"
          flags: --cpu=${{ inputs.cpu }} --memory=${{ inputs.memory }} --port=5000 --min-instances=${{ inputs.minimum_instances }} --network=${{ inputs.network_name }} --subnet=${{ inputs.subnet_name }} --allow-unauthenticated
          env_vars: ${{ inputs.cr-vars }}
          secrets: ${{ inputs.env-secrets }}
